version: '3.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:4.x-next
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
volumes:
  verdaccio:
    driver: local
